# Generated by Django 5.2 on 2025-04-29 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0004_vote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pvotes",
                to="post.post",
            ),
        ),
    ]
